export const attributeList = [
    // List grabbed from MDN web docs
    // https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
    'accept',
    'accept-charset',
    'accesskey',
    'action',
    'align',
    'allow',
    'alt',
    'async',
    'autocapitalize',
    'autocomplete',
    'autofocus',
    'autoplay',
    'background', // Deprecated
    'bgcolor', // Deprecated
    'border', // Deprecated
    'buffered',
    'challenge',
    'charset',
    'checked',
    'cite',
    // 'class', // Has it's own special case
    'code',
    'codebase',
    'color', // Deprecated
    'cols',
    'colspan',
    'content',
    'contenteditable',
    'contextmenu',
    'controls',
    'coords',
    'crossorigin',
    'csp', // exp
    'data',
    // 'data-*' Has it's own special case
    'datetime',
    'decoding',
    'default',
    'defer',
    'dir',
    'dirname',
    'disabled',
    'download',
    'draggable',
    'dropzone',
    'enctype',
    'enterkeyhint', // exp
    'for',
    'form',
    'formaction',
    'formenctype',
    'formmethod',
    'formnovalidate',
    'formtarget',
    'headers',
    'height',
    'hidden',
    'high',
    'href',
    'hreflang',
    'http-equiv',
    'icon',
    'id',
    'importance', // exp
    'integrity',
    'intrinsicsize', // exp
    'inputmode',
    'ismap',
    'itemprop',
    'keytype',
    'kind',
    'label',
    'lang',
    'language',
    'loading', // exp
    'list',
    'loop',
    'low',
    'manifest', // dep
    'max',
    'maxlength',
    'minlength',
    'media',
    'method',
    'min',
    'multiple',
    'muted',
    'name',
    'novalidate',
    'open',
    'optimum',
    'pattern',
    'ping',
    'placeholder',
    'poster',
    'preload',
    'radiogroup',
    'readonly',
    'referrerpolicy',
    'rel',
    'required',
    'reversed',
    'rows',
    'rowspan',
    'sandbox',
    'scope',
    'scoped',
    'selected',
    'shape',
    'size',
    'sizes',
    'slot',
    'span',
    'spellcheck',
    'src',
    'srcdoc',
    'srclang',
    'srcset',
    'start',
    'step',
    'style',
    'summary',
    'tabindex',
    'target',
    'title',
    'translate',
    'type',
    'usemap',
    'value',
    'width',
    'wrap'
];