language: node_js
node_js:
  - "node"

jobs:
  include:
    - stage: install
      script: npm install
      skip_cleanup: true
    - stage: test
      script:
        - npm run test
        - codecov -f coverage/*.json
      skip_cleanup: true
    - stage: dist
      script:
      - npm run dist
      - npx semantic-release
      if: branch = master